#this file initializes all images to be used in the project.
init:

    image title one = "./rsrc/title1.jpg"
    image title two = "./rsrc/title2.jpg"
    image title three = "./rsrc/title3.jpg"
    image title four = "./rsrc/title4.jpg"

    image intro one = "./rsrc/intro1.jpg"
    image intro two = "./rsrc/intro2.jpg"
    image intro three = "./rsrc/intro3.jpg"
    image intro four = "./rsrc/intro4.jpg"
    image intro five = "./rsrc/intro5.jpg"

    image matrix one = "./rsrc/matrix1.jpg"
    image matrix two = "./rsrc/matrix2.jpg"
    image matrix one_two = "./rsrc/matrix1.2.jpg"
    image matrix two_two = "./rsrc/matrix2.2.jpg"
    image matric three = "./rsrc/matrix3.jpg"

    image maze one = "./rsrc/maze1.jpg"
    image maze two = "./rsrc/maze2.jpg"
    image maze three = "./rsrc/maze3.jpg"
    image maze four = "./rsrc/maze4.jpg"
    image maze five = "./rsrc/maze5.jpg"
    image maze six = "./rsrc/maze6.jpg"
    image maze seven = "./rsrc/maze7.jpg"
    image maze eight = "./rsrc/maze8.jpg"
    image maze nine = "./rsrc/maze9.jpg"
    image maze ten = "./rsrc/maze10.jpg"
    image maze eleven = "./rsrc/maze11.jpg"
    image maze twelve = "./rsrc/maze12.jpg"
    image maze thirteen = "./rsrc/maze13.jpg"
    image maze fourteen = "./rsrc/maze14.jpg"
    image maze fifteen = "./rsrc/maze15.jpg"
    image maze sixteen = "./rsrc/maze16.jpg"
    image maze seventeen = "./rsrc/maze17.jpg"
